[package]
name = "icon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
css-color = "0.2.8"
icns = "0.3.1"
image = { workspace = true }
log = { version = "0.4.25", features = ["kv"] }
resvg = "0.44.0"
serde = "1.0.217"
serde_json = "1.0.137"
