name: Release

on:
  push:
    branches: ["release"]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: timer
jobs:
  build:
  strategy:
    matrix:
      include:
        - os: windows-latest
          rust-target: x86_64-pc-windows-msvc
          artifact-name: win64
          artifact-file: $APP_NAME.exe
          tar: false

        - os: windows-latest
          rust-target: i686-pc-windows-msvc
          artifact-name: win32
          artifact-file: $APP_NAME.exe
          tar: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@
        with:
        toolchain: stable-${{ matrix.rust-target }}

      - name: Build
        run: cargo build --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: $APP_NAME
          path: target/release/${{ matrix.artifact-file }}
